import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'kbajpai' at '7/16/16 8:15 AM' with Gradle 2.2.1
 *
 * @author kbajpai, @date 7/16/16 8:15 AM
 */
public class MainTest {
    @Test
    public void testSomeMethod() {
    }
}
